--liquibase formatted sql

--changeset Bainc:001

create table public.genres(id bigint generated by default as identity primary key not null,
                           title varchar(100));

create table public.pubhouses(id bigint generated by default as identity primary key not null,
                              title varchar(100));

create table public.tags(id bigint generated by default as identity primary key not null,
                         title varchar(100));
create table public.authors(id bigint generated by default as identity primary key not null,
                            surname varchar(25),
                            name varchar(25),
                            middlename varchar(25));

create table public.books(id bigint generated by default as identity primary key not null,
                          uuid uuid unique not null,
                          title varchar(100),
                          originaltitle varchar(100),
                          yearedition varchar(25),
                          isbnoriginal varchar(25),
                          isbntranslate varchar(25),
                          yearofeditiontranslate varchar(25),
                          fileformatbook smallint,
                          pathtozipbook varchar(255));

create table public.books_authors(book_id bigint not null, author_id bigint not null,
                                  constraint books_id foreign key(book_id) references public.books(id),
                                  constraint authors_id foreign key(author_id) references public.authors(id));

create table public.books_tags(book_id bigint not null, tag_id bigint not null,
                                  constraint books_id foreign key(book_id) references public.books(id),
                                  constraint tags_id foreign key(tag_id) references public.tags(id));


